### ISSUE TITLE
Jtrev23 Bug List for Windows

### ISSUE THREAD

**Issue by Jtrev23** [Tricky1975/Star-Story#351]
These are the main bugs/glitches I encountered during my play through

1) Game Crashes when the mother computer boss tries to attack (picture provided)
![sserrorpic2](https://cloud.githubusercontent.com/assets/17017310/12737914/37b9eff8-c92a-11e5-942b-c0ff0ded6b18.png) 
![sserrorpic1](https://cloud.githubusercontent.com/assets/17017310/12737915/37be3f04-c92a-11e5-9080-c60ddd313211.png)

These are the two screens that are shown after the boss tries to attack.

2) Upon entering a location the player is immediately swarmed by enemies. However the enemies are unable to reach the player because the other characters are blocking the way (picture provided)

![sserrorpic3](https://cloud.githubusercontent.com/assets/17017310/12737913/37b915f6-c92a-11e5-9d29-5d672b4672ca.png)
Ths happened to me just by entering that part of the level 

3) Unable to load a saved game, the game will attempt to load it and go back to the load game screen immediately. 

4) Less of a bug than others but game will crash if the player attempts to save the game without naming the save file.

**Comment by Tricky1975** [comment]
Bug 1) is already fixed, but not yet uploaded (see #349)
Bug 2) Yeah, especially the Yaqirpa dungeon has a few problems on this department. A little redesign is indeed in order
Bug 3) this one is fixed, however if you used the GameJolt client you need to uninstall the game and re-install it and this SHOULD work again. If not, then please hang on, then it will be fixed  in the next upload. (aside from the other bugs, this is indeed a Windows-Only bug).
Bug 4) Ah, I didn't know about that one. That should be easy enough to fix.
- [x] Crash on boss Yaqirpa (less than 3 char bug #349)
- [x] Enemies too much on second floor Yaqirpa
- [x] Loading not possible
- [x] Savegame no name => crash

**Comment by Tricky1975** [comment]
Enemy issue should now also be less annoying. I also added a maximum radius in which enemies will follow you, making escaping them somehow easier. In #353 I also have a plan to make the enemies also less oppressive. I was not fully happy about the enemy chase routines myself you know ;wink:

And with that I can close this issue. Of course everything will take effect AFTER the new version is uploaded, which will happen after the next test. I will let you know when that happens ;)

**Comment by Jtrev23** [comment]
Alright, keep up great the work!

**Comment by Tricky1975** [comment]
The new upload is done. On both GameJolt and Sourceforge a version that should be playable until you obtain your own spaceship can be downloaded for both Mac and Windows.
Thanks for the encouragement and for reporting that stuff.

**Comment by Jtrev23** [comment]
Alright, I'll have a follow up review ready by next week.
