### ISSUE TITLE
Move repository to the "Phantasar Productions" organisation

### ISSUE THREAD

**Issue by Tricky1975** [Tricky1975/Star-Story#470]
This was planned from the start, but as I did have pretty little repositories it didn't seen needed back then, but now.... :(
- [x] Move Repository itself
- [x] Adept links on Star Story Website
- [x] Edit Game Jolt Links
- [x] Edit settings off-line part

**Comment by Tricky1975** [comment]
Game Jolt set. The game's site is for tomorrow. GitHub will redirect here for the time being anyway, so there's no rush. ;)

**Comment by TrickyRachel** [comment]
Test

**Comment by Tricky1975** [comment]
All done... Yeah, I was not in a hurry for this one, sorry. 😝
