### ISSUE TITLE
Items un-obtainable inside a wall.

### ISSUE THREAD

**Issue by ghost** [Tricky1975/Star-Story#475]
misplaced item in Area 002
![nayttokuva 2016-07-06 kello 21 51 14](https://cloud.githubusercontent.com/assets/20288180/16630667/18b98162-43c4-11e6-9a8e-8dc99629366a.png)

**Comment by Tricky1975** [comment]
Fixed.
This one might be encountered in other dungeons as well,though, as this easily happens when Kthura starts lagging during level design.
