### ISSUE TITLE
House can be entered from behind the door

### ISSUE THREAD

**Issue by ghost** [Tricky1975/Star-Story#484]
this house can be entered by going behind it and then walking on the square the door is on, there is no door behind the house (as seen on the inside) so the house should not be able to be entered from behind. The house is in area 004
![nayttokuva 2016-07-07 kello 15 56 19](https://cloud.githubusercontent.com/assets/20288180/16653937/1d13e82c-445c-11e6-8566-91de2c649978.png)

**Comment by Tricky1975** [comment]
This is in the "Belioss" dungeon, right?

**Comment by Tricky1975** [comment]
Fixed ;)
