### ISSUE TITLE
Door acting weird.

### ISSUE THREAD

**Issue by ghost** [Tricky1975/Star-Story#492]
this door in area 018 is acting really weird. (2 screenshots)
![screen shot 2016-07-09 at 20 27 48](https://cloud.githubusercontent.com/assets/20288180/16709262/efaa3ec2-4613-11e6-9caa-0ecec8d50915.png)
![screen shot 2016-07-09 at 20 27 28](https://cloud.githubusercontent.com/assets/20288180/16709261/efa9b5ec-4613-11e6-909b-0e7a694b0110.png)

**Comment by Tricky1975** [comment]
Fixed ;)
