### ISSUE TITLE
Secret dungeon entrance not visible when entered

### ISSUE THREAD

**Issue by ghost** [Tricky1975/Star-Story#496]
EDIT: actually I just happened to find a spot to get out of bounds in a place I thought was the secret dungeon
![screen shot 2016-07-12 at 18 58 30](https://cloud.githubusercontent.com/assets/20288180/16774002/c7b043d4-4862-11e6-9269-be88df863f80.png)

**Comment by Tricky1975** [comment]
Very likely, there was a "hole in the blockmap" there. All nature dungeons suffer from that. Mostly I manage to fix all these "holes" but sometimes one "slips" through.

**Comment by Tricky1975** [comment]
And I was right. What you found was not the entrance to the secret dungeon, but a breach in the blockmap as a wrong spot. This has been fixed now.
