### ISSUE TITLE
Phantasar shop needs scrolling

### ISSUE THREAD

**Issue by Tricky1975** [Tricky1975/Star-Story#570]

**Comment by TrickyRachel** [comment]
Right... time to tackle this one.

**Comment by TrickyRachel** [comment]
![](https://avatars1.githubusercontent.com/u/6297959?v=3&s=88)
- Scroll arrows done
- Arrows should appear now
- FIXED: 'nil'
- The arrows should work now, if so I can close this issue and go for the first stable release, whooohooo!

**Comment by TrickyRachel** [comment]
IT WORKS!!!
This issue can be closed, and next stop is to prepare the first stable release... whooohooo!
